# Generated by Django 5.2.4 on 2025-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('balance_brought_forward', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_members', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_traders', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_sick_death', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_donors', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('withdrawal_from_treasurer', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('Jan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Feb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Mar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Apr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('May', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Jun', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Jul', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Aug', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Sep', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Oct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Nov', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Dec', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TraderContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('amount_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_months_subscribed', models.IntegerField(default=0)),
                ('Jan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Feb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Mar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Apr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('May', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Jun', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Jul', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Aug', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Sep', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Oct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Nov', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Dec', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
